CREATE TABLE TB_MUSIC (
    ID INT IDENTITY(1,1),
    NAME VARCHAR(200),
    SINGER VARCHAR(200),
    RELEASE_DATE DATE
);

ALTER TABLE TB_MUSIC
ADD CONSTRAINT PK_TB_MUSIC PRIMARY KEY (ID);

INSERT INTO TB_MUSIC (NAME, SINGER , RELEASE_DATE) VALUES ('Lost in Japan', 'Shawn Mendes', '2018-03-23');
INSERT INTO TB_MUSIC (NAME, SINGER , RELEASE_DATE) VALUES ('Photograph', 'Ed Sheeran', '2015-05-11');
INSERT INTO TB_MUSIC (NAME, SINGER , RELEASE_DATE) VALUES ('Theres Nothing Holdin Me Back', 'Shawn Mendes', '2017-04-20');
INSERT INTO TB_MUSIC (NAME, SINGER , RELEASE_DATE) VALUES ('In My Blood', 'Shawn Mendes', '2018-03-22');