CREATE TABLE TB_MUSIC (
    ID INT IDENTITY(1,1),
    NAME VARCHAR(200),
    SINGER VARCHAR(200),
    RELEASE_DATE DATE,
	ATIVO CHAR(1) DEFAULT '1'
);

ALTER TABLE TB_MUSIC
ADD CONSTRAINT PK_TB_MUSIC PRIMARY KEY (ID);

INSERT INTO TB_MUSIC (NAME, SINGER , RELEASE_DATE, ATIVO) VALUES ('Lost in Japan', 'Shawn Mendes', '2018-03-23','1');
INSERT INTO TB_MUSIC (NAME, SINGER , RELEASE_DATE, ATIVO) VALUES ('Photograph', 'Ed Sheeran', '2015-05-11','1');
INSERT INTO TB_MUSIC (NAME, SINGER , RELEASE_DATE, ATIVO) VALUES ('Theres Nothing Holdin Me Back', 'Shawn Mendes', '2017-04-20','1');
INSERT INTO TB_MUSIC (NAME, SINGER , RELEASE_DATE, ATIVO) VALUES ('In My Blood', 'Shawn Mendes', '2018-03-22','1');