-- Criação da tabela TB_MUSIC
CREATE TABLE TB_MUSIC (
    ID INT IDENTITY(1,1),
    NAME VARCHAR(200),
    SINGER VARCHAR(200) NOT NULL,
    STYLE_ID INT,
    RELEASE_DATE DATE,
	ACTIVE CHAR(1) DEFAULT '1'
);

-- Criação da tabela de domínio TB_STYLES
CREATE TABLE TB_STYLES (
    ID INT NOT NULL,
    NAME VARCHAR(50) NOT NULL
);

-- Adição de constraints para PK e FK
ALTER TABLE TB_MUSIC
ADD CONSTRAINT PK_TB_MUSIC PRIMARY KEY (ID);

ALTER TABLE TB_STYLES
ADD CONSTRAINT PK_TB_STYLE PRIMARY KEY (ID);

ALTER TABLE TB_MUSIC
ADD CONSTRAINT FK_TB_MUSIC_STYLE 
FOREIGN KEY (ID)
REFERENCES TB_MUSIC (ID);

-- carga inicial de TB_STYLES
INSERT INTO TB_STYLES (ID, NAME) VALUES (1, 'Pop');
INSERT INTO TB_STYLES (ID, NAME) VALUES (2, 'Synthwave');
INSERT INTO TB_STYLES (ID, NAME) VALUES (3, 'Funk');
INSERT INTO TB_STYLES (ID, NAME) VALUES (4, 'Soul');
INSERT INTO TB_STYLES (ID, NAME) VALUES (5, 'Reggaeton');
INSERT INTO TB_STYLES (ID, NAME) VALUES (6, 'Electropop');
INSERT INTO TB_STYLES (ID, NAME) VALUES (7, 'Rock');
INSERT INTO TB_STYLES (ID, NAME) VALUES (8, 'Electronic');
INSERT INTO TB_STYLES (ID, NAME) VALUES (9, 'Reggae Fusion');
INSERT INTO TB_STYLES (ID, NAME) VALUES (10, 'Metalcore');

-- carga inicial de TB_MUSIC
INSERT INTO TB_MUSIC (NAME, SINGER, RELEASE_DATE, STYLE_ID, ACTIVE) VALUES ('Lost in Japan', 'Shawn Mendes', '2018-03-23', 1, '1');
INSERT INTO TB_MUSIC (NAME, SINGER, RELEASE_DATE, STYLE_ID, ACTIVE) VALUES ('Photograph', 'Ed Sheeran', '2015-05-11', 1, '1');
INSERT INTO TB_MUSIC (NAME, SINGER, RELEASE_DATE, STYLE_ID, ACTIVE) VALUES ('There is Nothing Holdin Me Back', 'Shawn Mendes', '2017-04-20', 1, '1');
INSERT INTO TB_MUSIC (NAME, SINGER, RELEASE_DATE, STYLE_ID, ACTIVE) VALUES ('In My Blood', 'Shawn Mendes', '2018-03-22', 1, '1');
INSERT INTO TB_MUSIC (NAME, SINGER, RELEASE_DATE, STYLE_ID, ACTIVE) VALUES ('Shape of You', 'Ed Sheeran', '2017-01-06', 1, '1');
INSERT INTO TB_MUSIC (NAME, SINGER, RELEASE_DATE, STYLE_ID, ACTIVE) VALUES ('Blinding Lights', 'The Weeknd', '2019-11-29', 2, '1');
INSERT INTO TB_MUSIC (NAME, SINGER, RELEASE_DATE, STYLE_ID, ACTIVE) VALUES ('Uptown Funk', 'Mark Ronson ft. Bruno Mars', '2014-11-10', 3, '1');
INSERT INTO TB_MUSIC (NAME, SINGER, RELEASE_DATE, STYLE_ID, ACTIVE) VALUES ('Hello', 'Adele', '2015-10-23', 4, '1');
INSERT INTO TB_MUSIC (NAME, SINGER, RELEASE_DATE, STYLE_ID, ACTIVE) VALUES ('Levitating', 'Dua Lipa', '2020-03-27', 1, '1');
INSERT INTO TB_MUSIC (NAME, SINGER, RELEASE_DATE, STYLE_ID, ACTIVE) VALUES ('Havana', 'Camila Cabello ft. Young Thug', '2017-08-03', 5, '1');
INSERT INTO TB_MUSIC (NAME, SINGER, RELEASE_DATE, STYLE_ID, ACTIVE) VALUES ('Bad Guy', 'Billie Eilish', '2019-03-29', 6, '1');
INSERT INTO TB_MUSIC (NAME, SINGER, RELEASE_DATE, STYLE_ID, ACTIVE) VALUES ('Dance Monkey', 'Tones and I', '2019-05-10', 1, '1');
INSERT INTO TB_MUSIC (NAME, SINGER, RELEASE_DATE, STYLE_ID, ACTIVE) VALUES ('Someone Like You', 'Adele', '2011-01-24', 4, '1');
INSERT INTO TB_MUSIC (NAME, SINGER, RELEASE_DATE, STYLE_ID, ACTIVE) VALUES ('Rolling in the Deep', 'Adele', '2010-11-29', 4, '1');
INSERT INTO TB_MUSIC (NAME, SINGER, RELEASE_DATE, STYLE_ID, ACTIVE) VALUES ('Cedo ou Tarde', 'NX Zero', '2009-06-22', 7, '1');
INSERT INTO TB_MUSIC (NAME, SINGER, RELEASE_DATE, STYLE_ID, ACTIVE) VALUES ('Sorry', 'Justin Bieber', '2015-10-23', 1, '1');
INSERT INTO TB_MUSIC (NAME, SINGER, RELEASE_DATE, STYLE_ID, ACTIVE) VALUES ('Numb', 'Linkin Park', '2003-09-08', 7, '1');
INSERT INTO TB_MUSIC (NAME, SINGER, RELEASE_DATE, STYLE_ID, ACTIVE) VALUES ('O Sol', 'Vitor Kley', '2018-08-10', 1, '1');
INSERT INTO TB_MUSIC (NAME, SINGER, RELEASE_DATE, STYLE_ID, ACTIVE) VALUES ('Someone You Loved', 'Lewis Capaldi', '2018-11-08', 1, '1');
INSERT INTO TB_MUSIC (NAME, SINGER, RELEASE_DATE, STYLE_ID, ACTIVE) VALUES ('Fight Back', 'Neffex', '2018-08-01', 8, '1');
INSERT INTO TB_MUSIC (NAME, SINGER, RELEASE_DATE, STYLE_ID, ACTIVE) VALUES ('Rise Up', 'Voilá', '2019-07-12', 1, '1');
INSERT INTO TB_MUSIC (NAME, SINGER, RELEASE_DATE, STYLE_ID, ACTIVE) VALUES ('Uptown Funk', 'Bruno Mars', '2014-11-10', 3, '1');
INSERT INTO TB_MUSIC (NAME, SINGER, RELEASE_DATE, STYLE_ID, ACTIVE) VALUES ('Razões e Emoções', 'NX Zero', '2006-03-20', 7, '1');
INSERT INTO TB_MUSIC (NAME, SINGER, RELEASE_DATE, STYLE_ID, ACTIVE) VALUES ('Deixa Ela Entrar', 'Pitty', '2009-09-01', 7, '1');
INSERT INTO TB_MUSIC (NAME, SINGER, RELEASE_DATE, STYLE_ID, ACTIVE) VALUES ('What Do You Mean?', 'Justin Bieber', '2015-08-28', 1, '1');
INSERT INTO TB_MUSIC (NAME, SINGER, RELEASE_DATE, STYLE_ID, ACTIVE) VALUES ('In the End', 'Linkin Park', '2001-10-09', 7, '1');
INSERT INTO TB_MUSIC (NAME, SINGER, RELEASE_DATE, STYLE_ID, ACTIVE) VALUES ('Vapor', 'Vitor Kley', '2019-11-08', 1, '1');
INSERT INTO TB_MUSIC (NAME, SINGER, RELEASE_DATE, STYLE_ID, ACTIVE) VALUES ('Before You Go', 'Lewis Capaldi', '2020-01-17', 1, '1');
INSERT INTO TB_MUSIC (NAME, SINGER, RELEASE_DATE, STYLE_ID, ACTIVE) VALUES ('Naked', 'James Arthur', '2017-10-20', 1, '1');
INSERT INTO TB_MUSIC (NAME, SINGER, RELEASE_DATE, STYLE_ID, ACTIVE) VALUES ('Destiny', 'Neffex', '2019-02-22', 8, '1');
INSERT INTO TB_MUSIC (NAME, SINGER, RELEASE_DATE, STYLE_ID, ACTIVE) VALUES ('Never Gonna Give You Up', 'Voilá', '2020-11-20', 1, '1');
INSERT INTO TB_MUSIC (NAME, SINGER, RELEASE_DATE, STYLE_ID, ACTIVE) VALUES ('Na Sua Estante', 'Pitty', '2005-05-02', 7, '1');
INSERT INTO TB_MUSIC (NAME, SINGER, RELEASE_DATE, STYLE_ID, ACTIVE) VALUES ('Morena', 'Vitor Kley', '2021-06-04', 1, '1');
INSERT INTO TB_MUSIC (NAME, SINGER, RELEASE_DATE, STYLE_ID, ACTIVE) VALUES ('Table for One', 'Voilá', '2023-02-24', 1, '1');
INSERT INTO TB_MUSIC (NAME, SINGER, RELEASE_DATE, STYLE_ID, ACTIVE) VALUES ('Just the Way You Are', 'Bruno Mars', '2010-10-05', 1, '1');
INSERT INTO TB_MUSIC (NAME, SINGER, RELEASE_DATE, STYLE_ID, ACTIVE) VALUES ('Grenade', 'Bruno Mars', '2010-10-25', 1, '1');
INSERT INTO TB_MUSIC (NAME, SINGER, RELEASE_DATE, STYLE_ID, ACTIVE) VALUES ('Locked Out of Heaven', 'Bruno Mars', '2012-10-01', 1, '1');
INSERT INTO TB_MUSIC (NAME, SINGER, RELEASE_DATE, STYLE_ID, ACTIVE) VALUES ('Drown', 'Bring Me The Horizon', '2015-11-05', 10, '1');
INSERT INTO TB_MUSIC (NAME, SINGER, RELEASE_DATE, STYLE_ID, ACTIVE) VALUES ('Sleepwalking', 'Bring Me The Horizon', '2013-04-29', 10, '1');
INSERT INTO TB_MUSIC (NAME, SINGER, RELEASE_DATE, STYLE_ID, ACTIVE) VALUES ('Can You Feel My Heart', 'Bring Me The Horizon', '2013-11-11', 10, '1');
INSERT INTO TB_MUSIC (NAME, SINGER, RELEASE_DATE, STYLE_ID, ACTIVE) VALUES ('Rude', 'MAGIC!', '2013-07-01', 9, '1');
INSERT INTO TB_MUSIC (NAME, SINGER, RELEASE_DATE, STYLE_ID, ACTIVE) VALUES ('Let Your Hair Down', 'MAGIC!', '2014-09-29', 9, '1');
INSERT INTO TB_MUSIC (NAME, SINGER, RELEASE_DATE, STYLE_ID, ACTIVE) VALUES ('No Way No', 'MAGIC!', '2015-05-18', 9, '1');